print("hello, world")
name = input()
print("hello there "+name)
print("What's your favorite color")
color = input()
print ("my favorite color is "+ color)
print ("favorite sport")
sport = input()
print ("my favorite sport is "+ sport)
print ("what's your favorite food")
food = input()
print ("my favorite food is "+ food)